export const HOURLY: [string, string][] = [
  ["Mittlere Windgeschwindigkeit in ca. 10 m Höhe [m/s]", "F_MN003"],
  ["Mittlere Windrichtung in ca. 10 m Höhe [°]", "D_MN003"],
  ["Erdbodentemperatur in 10 cm Tiefe [°C]", "TE10_MN002"],
  ["Erdbodentemperatur in 100 cm Tiefe [°C]", "TE100_MN002"],
  ["Erdbodentemperatur in 20 cm Tiefe [°C]", "TE20_MN002"],
  ["Erdbodentemperatur in 5 cm Tiefe [°C]", "TE05_MN002"],
  ["Erdbodentemperatur in 50 cm Tiefe [°C]", "TE50_MN002"],
  ["Lufttemperatur auf 2 m Höhe [°C]", "TT_TU_MN009"],
  ["Niederschlagsform (WR-Code)", "WRTR_MN008"],
  ["Niederschlagshöhe [mm]", "R1_MN008"],
  ["Taupunkttemperatur auf 2 m Höhe [°C]", "TD_MN008"],
  ["Windgeschwindigkeit in 10 m Höhe [m/s]", "FF_MN008"],
  ["Windrichtung in 10 m Höhe [°]", "DD_MN008"],
  ["Relative Feuchte [%]", "RF_TU_MN009"],
  ["Bedeckungsgrad [Achtel]", "N_MN008"],
  ["Indikator ob Niederschlag gefallen ist", "RS_IND_MN008"],
  ["Luftdruck auf Stationshöhe [hpa]", "P0_MN008"],
  ["Luftdruck reduziert auf Meereshöhe [hpa]", "P_MN008"]
]

export const DAILY: [string, string][] = [
  ["Tagesmittel der mittleren Windgeschwindigkeit in ca. 10 m Höhe [m/s]", "FM_MN003"],
  ["Tagesmittel der relativen Feuchte auf 2 m Höhe [%]", "UPM_MN004"],
  ["Summe der Neuschneehöhe [cm]", "NSH_TAG_MN006"],
  ["Niederschlagshöhe [mm]", "RSK_MN004"],
  ["Strahlung und Sonnenscheindauer [h]", "SD_MN007"],
  ["Schneehöhe [cm]", "SHK_TAG_MN004"],
  ["Niederschlagsform", "RSF_MN006"],
  ["Niederschlagshöhe [mm]", "RS_MN006"],
  ["Schneehöhe [cm]", "SH_TAG_MN006"],
  ["Höhe des ausgestochenen Schnees [cm]", "ASH_MN006"],
  ["Sonnenscheindauer [h]", "SDK_MN004"],
  ["Maximale Windspitze in ca. 10 m Höhe [m/s]", "FX_MN003"],
  ["Mittlere Lufttemperatur auf 2 m Höhe [°C]", "TMK_MN004"],
  ["Maximum der Lufttemperatur auf 2 m Höhe [°C]", "TXK_MN004"],
  ["Minimum der Lufttemperatur am Erdboden (5 cm Höhe) [°C]", "TGK_MN004"],
  ["Minimum der Lufttemperatur auf 2 m Höhe [°C]", "TNK_MN004"],
  ["Wasseräquivalent der Gesamtschneedecke [mm]", "WASH_MN006"],
  ["Wasseräquivalent der ausgestochenen Schneedecke [mm]", "WAAS_MN006"],
  ["Mittlerer Bedeckungsgrad [Achtel]", "NM_MN004"],
  ["Mittlerer Dampfdrucks [hpa]", "VPM_MN004"],
  ["Mittlerer Luftdruck auf Stationshöhe [hpa]", "PM_MN004"]
]

export const MONTHLY: [string, string][] = [
  ["Mittel der Lufttemperatur auf 2 m Höhe [°C]", "MO_TT_MN004"],
  ["Mittel der Sonnenscheindauer [h]", "MO_SD_MN004"],
  ["Mittel der Windstärke [bft]", "MO_FK_MN004"],
  ["Mittel der relativen Feuchte auf 2 m Höhe [%]", "MO_RF_MN004"],
  ["Mittel des Bedeckungsgrades [Achtel]", "MO_N_MN004"],
  ["Mittel des Dampfdrucks [hpa]", "MO_VPM_MN004"],
  ["Mittel des Luftdrucks auf Stationshöhe [hpa]", "MO_P0_MN004"],
  ["Mittel des Tagesmaximums der Lufttemperatur auf 2 m Höhe [°C]", "MO_TX_MN004"],
  ["Mittel des Tagesminimums der Lufttemperatur am Erdboden in 5 cm  Höhe [°C]", "MO_EBM_MN004"],
  ["Mittel des Tagesminimums der Lufttemperatur auf 2 m Höhe [°C]", "MO_TN_MN004"],
  ["Summe der Neuschneehöhe [cm]", "MO_NSH_MN006"],
  ["Summe der Niederschlagshöhe [mm]", "MO_RR_MN006"],
  ["Summe der Schneehöhe [cm]", "MO_SH_S_MN006"],
  ["Summe der Sonnenscheindauer [h]", "MO_SD_S_MN004"]
]

export const YEARLY: [string, string][] = [
  ["Mittel der Lufttemperatur auf 2 m Höhe [°C]", "JA_TT_MN004"],
  ["Mittel der Sonnenscheindauer [h]", "JA_SD_MN004"],
  ["Mittel der Windstärke [bft]", "JA_FK_MN004"],
  ["Mittel der relativen Feuchte auf 2 m Höhe [%]", "JA_RF_MN004"],
  ["Mittel des Bedeckungsgrades [Achtel]", "JA_N_MN004"],
  ["Mittel des Dampfdrucks [hpa]", "JA_VPM_MN004"],
  ["Mittel des Luftdrucks auf Stationshöhe [hpa]", "JA_P0_MN004"],
  ["Mittel des Tagesmaximums der Lufttemperatur auf 2 m Höhe [°C]", "JA_TX_MN004"],
  ["Mittel des Tagesminimums der Lufttemperatur am Erdboden in 5 cm Höhe [°C]", "JA_EBM_MN004"],
  ["Mittel des Tagesminimums der Lufttemperatur auf 2 m Höhe [°C]", "JA_TN_MN004"],
  ["Summe der Neuschneehöhe [cm]", "JA_NSH_MN006"],
  ["Summe der Niederschlagshöhe [mm]", "JA_RR_MN006"],
  ["Summe der Schneehöhe [cm]", "JA_SH_S_MN006"],
  ["Summe der Sonnenscheindauer [h]", "JA_SD_S_MN004"],
  ["Gebietsmittlere Lufttemperatur (Mittel) [°C] (2 m Höhe)", "RGN_DEU_P1Y_TM"],
  ["Gebietsmittlere Niederschlagshöhe (Jahressumme) [mm]", "RGN_DEU_P1Y_RR"],
  ["Gebietsmittlere Sonnenscheindauer (Jahressumme) [h]", "RGN_DEU_P1Y_SD"]
]