export const HOURLY:[string, string][] = [
 ["F_MN003", "Stundenmittel der Stationsmessungen der Windgeschwindigkeit in ca. 10 m Höhe in m/s"],
 ["D_MN003", "Stundenmittel der Stationsmessungen der Windrichtung in ca. 10 m Höhe in Grad"],
 ["TE10_MN002", "Stündliche Stationsmessungen der Erdbodentemperatur in 10 cm Tiefe in °C" ],
 ["TE100_MN002",  "Stündliche Stationsmessungen der Erdbodentemperatur in 100 cm Tiefe in °C"],
 ["TE20_MN002", "Stündliche Stationsmessungen der Erdbodentemperatur in 20 cm Tiefe in °C"],
 ["TE05_MN002","Stündliche Stationsmessungen der Erdbodentemperatur in 5 cm Tiefe in °C"],
 ["TE50_MN002",  "Stündliche Stationsmessungen der Erdbodentemperatur in 50 cm Tiefe in °C" ],
 ["TT_TU_MN009",  "Stündliche Stationsmessungen der Lufttemperatur auf 2 m Höhe in °C" ],
 ["WRTR_MN008", "Stündliche Stationsmessungen der Niederschlagsform (WR-Code)" ],
 ["R1_MN008",  "Stündliche Stationsmessungen der Niederschlagshöhe in mm" ],
 ["TD_MN008", "Stündliche Stationsmessungen der Taupunkttemperatur auf 2 m Höhe in °C" ],
 ["FF_MN008", "Stündliche Stationsmessungen der Windgeschwindigkeit in 10 m Höhe in m/s" ],
 ["DD_MN008", "Stündliche Stationsmessungen der Windrichtung in 10 m Höhe in Grad" ],
 ["RF_TU_MN009", "Stündliche Stationsmessungen der relativen Feuchte in %" ],
 ["N_MN008","Stündliche Stationsmessungen des Bedeckungsgrades in Achtel" ],
 ["RS_IND_MN008", "Stündliche Stationsmessungen des Indikators ob Niederschlag gefallen" ],
 ["P0_MN008", "Stündliche Stationsmessungen des Luftdruckes auf Stationshöhe in hpa" ],
 ["P_MN008", "Stündliche Stationsmessungen des Luftdruckes reduziert auf Meereshöhe in hpa"]
]
