export const HOURLY:[string, string][] = [
  ["F_MN003", "Mittlere Windgeschwindigkeit in ca. 10 m Höhe [m/s]" ],
  ["D_MN003", "Mittlere Windrichtung in ca. 10 m Höhe [°]" ],
  ["TE10_MN002", "Erdbodentemperatur in 10 cm Tiefe [°C]" ],
  ["TE100_MN002", "Erdbodentemperatur in 100 cm Tiefe [°C]" ],
  ["TE20_MN002", "Erdbodentemperatur in 20 cm Tiefe [°C]" ],
  ["TE05_MN002", "Erdbodentemperatur in 5 cm Tiefe [°C]" ],
  ["TE50_MN002", "Erdbodentemperatur in 50 cm Tiefe [°C]" ],
  ["TT_TU_MN009", "Lufttemperatur auf 2 m Höhe [°C]" ],
  ["WRTR_MN008", "Niederschlagsform (WR-Code)" ],
  ["R1_MN008", "Niederschlagshöhe [mm]" ],
  ["TD_MN008", "Taupunkttemperatur auf 2 m Höhe [°C]" ],
  ["FF_MN008", "Windgeschwindigkeit in 10 m Höhe [m/s]" ],
  ["DD_MN008", "Windrichtung in 10 m Höhe [°]" ],
  ["RF_TU_MN009", "Relative Feuchte [%]" ],
  ["N_MN008", "Bedeckungsgrad [Achtel]" ],
  ["RS_IND_MN008", "Indikator ob Niederschlag gefallen ist" ],
  ["P0_MN008", "Luftdruck auf Stationshöhe [hpa]" ],
  ["P_MN008", "Luftdruck reduziert auf Meereshöhe [hpa]" ]
]

export const DAILY:[string, string][] = [
  ["FM_MN003", "TagesMittel der mittleren Windgeschwindigkeit in ca. 10 m Höhe [m/s]" ],
  ["UPM_MN004", "Tagesmittel der relativen Feuchte auf 2 m Höhe [%]" ],
  ["NSH_TAG_MN006", "Summe der Neuschneehöhe [cm]" ],
  ["RSK_MN004", "Niederschlagshöhe [mm]" ],
  ["SD_MN007", "Strahlung und Sonnenscheindauer [h]" ],
  ["SHK_TAG_MN004", "Schneehöhe [cm]" ],
  ["RSF_MN006", "Niederschlagsform" ],
  ["RS_MN006", "Niederschlagshöhe [mm]" ],
  ["SH_TAG_MN006", "Schneehöhe [cm]" ],
  ["ASH_MN006", "Höhe des ausgestochenen Schnees [cm]" ],
  ["SDK_MN004", "Sonnenscheindauer [h]" ],
  ["FX_MN003", "Maximale Windspitze in ca. 10 m Höhe [m/s]" ],
  ["TMK_MN004", "Mittlere Lufttemperatur auf 2 m Höhe [°C]" ],
  ["TXK_MN004", "Maximum der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["TGK_MN004", "Minimum der Lufttemperatur am Erdboden (5 cm Höhe) [°C]" ],
  ["TNK_MN004", "Minimum der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["WASH_MN006", "Wasseräquivalent der Gesamtschneedecke [mm]" ],
  ["WAAS_MN006", "Wasseräquivalent der ausgestochenen Schneedecke [mm]" ],
  ["NM_MN004", "Mittlerer Bedeckungsgrad [Achtel]" ],
  ["VPM_MN004", "Mittlerer Dampfdrucks [hpa]" ],
  ["PM_MN004", "Mittlerer Luftdruck auf Stationshöhe [hpa]" ]
  ]

export const MONTHLY:[string, string][] = [
  ["MO_TT_MN004", "Mittel der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["MO_SD_MN004", "Mittel der Sonnenscheindauer [h]" ],
  ["MO_FK_MN004", "Mittel der Windstärke [bft]" ],
  ["MO_RF_MN004", "Mittel der relativen Feuchte auf 2 m Höhe [%]" ],
  ["MO_N_MN004", "Mittel des Bedeckungsgrades [Achtel]" ],
  ["MO_VPM_MN004", "Mittel des Dampfdrucks [hpa]" ],
  ["MO_P0_MN004", "Mittel des Luftdrucks auf Stationshöhe [hpa]" ],
  ["MO_TX_MN004", "Mittel des Tagesmaximums der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["MO_EBM_MN004", "Mittel des Tagesminimums der Lufttemperatur am Erdboden in 5 cm  Höhe [°C]" ],
  ["MO_TN_MN004", "Mittel des Tagesminimums der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["MO_NSH_MN006", "Summe der Neuschneehöhe [cm]" ],
  ["MO_RR_MN006", "Summe der Niederschlagshöhe [mm]" ],
  ["MO_SH_S_MN006", "Summe der Schneehöhe [cm]" ],
  ["MO_SD_S_MN004", "Summe der Sonnenscheindauer [h]" ]
]

export const YEARLY:[string, string][] = [
  ["JA_TT_MN004", "Mittel der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["JA_SD_MN004", "Mittel der Sonnenscheindauer [h]" ],
  ["JA_FK_MN004", "Mittel der Windstärke [bft]" ],
  ["JA_RF_MN004", "Mittel der relativen Feuchte auf 2 m Höhe [%]" ],
  ["JA_N_MN004", "Mittel des Bedeckungsgrades [Achtel]" ],
  ["JA_VPM_MN004", "Mittel des Dampfdrucks [hpa]" ],
  ["JA_P0_MN004", "Mittel des Luftdrucks auf Stationshöhe [hpa]" ],
  ["JA_TX_MN004", "Mittel des Tagesmaximums der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["JA_EBM_MN004", "Mittel des Tagesminimums der Lufttemperatur am Erdboden in 5 cm Höhe [°C]" ],
  ["JA_TN_MN004", "Mittel des Tagesminimums der Lufttemperatur auf 2 m Höhe [°C]" ],
  ["JA_NSH_MN006", "Summe der Neuschneehöhe [cm]" ],
  ["JA_RR_MN006", "Summe der Niederschlagshöhe [mm]" ],
  ["JA_SH_S_MN006", "Summe der Schneehöhe [cm]" ],
  ["JA_SD_S_MN004", "Summe der Sonnenscheindauer [h]" ],
  ["RGN_DEU_P1Y_TM", "Gebietsmittlere Lufttemperatur (Mittel) [°C] (2 m Höhe)" ],
  ["RGN_DEU_P1Y_RR", "Gebietsmittlere Niederschlagshöhe (Jahressumme) [mm]" ],
  ["RGN_DEU_P1Y_SD", "Gebietsmittlere Sonnenscheindauer (Jahressumme) [h]" ]
]
